parameters:
    ibexa.graphql.schema.ibexa_dir: "%kernel.project_dir%/var/graphql/types"

overblog_graphql:
    definitions:
        mappings:
            auto_discover: false
            types:
                -   type: yaml
                    dir: "%kernel.project_dir%/var/graphql/types"
                    suffix: ~
