# You can safely delete this file to disable welcome page
ibexa:
    system:
        site:
            content_view:
                full:
                    welcome_page:
                        template: "@ibexadesign/full/welcome_page.html.twig"
                        match:
                            Id\Location: 2
                        params:
                            project_dir: '%kernel.project_dir%'
                    photo_folder:
                        controller: 'App\Actions\Full\PhotoFolder'
                        template: "@ibexadesign/full/photo_folder.html.twig"
                        match:
                            Identifier\ContentType: 'photo_folder'
                        params:
                            project_dir: '%kernel.project_dir%'
