version: "3.2"
services:
    php-fpm:
        build:
            context: './docker/php/'
            args:
                UID: ${UID}
                GID: ${GID}
        volumes:
            - './:/var/www/app:rw'
            - '~/.cache/composer:/var/www/.composer:rw'
        container_name: ${CONTAINER_NAME}_php-fpm
        extra_hosts:
            -   "host.docker.internal:host-gateway"
        environment:
            PHP_IDE_CONFIG: "serverName=app"
            # Exposes BLACKFIRE_SERVER_* environment variables from the host
            BLACKFIRE_SERVER_ID: ~
            BLACKFIRE_SERVER_TOKEN: ~
        working_dir: /var/www/app
        links:
            - mysql
            - maildev
#    blackfire:
#        image: blackfire/blackfire:2
#        environment:
#            # Exposes BLACKFIRE_SERVER_* environment variables from the host
#            BLACKFIRE_SERVER_ID: ~
#            BLACKFIRE_SERVER_TOKEN: ~
    apache:
        build:
            context: './docker/apache/'
        links:
            - php-fpm
        depends_on:
            - php-fpm
        ports:
            - "${APACHE_PORT}:80"
        volumes:
            - './:/var/www/app:rw'
        container_name: ${CONTAINER_NAME}_apache
    mysql:
        image: mariadb:10.9.4
        ports:
            - '${MYSQL_PORT}:3306'
        volumes:
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
        container_name: ${CONTAINER_NAME}_mysql
    maildev:
        image: djfarrelly/maildev
        ports:
            - '${MAILDEV_PORT}:80'
        container_name: ${CONTAINER_NAME}_maildev
    node:
        container_name: ${CONTAINER_NAME}_nodejs
        build: './docker/node'
        links:
            - php-fpm
        volumes:
            - './:/var/www/app:rw'
        working_dir: /var/www/app
