# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.photo_folder_path: '%env(resolve:PHOTO_FOLDER_PATH)%'
    app.photo_variation_cache_path: '%env(resolve:PHOTO_VARIATION_CACHE_PATH)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $photoFolderPath: '%app.photo_folder_path%'
            $photoVariationCachePath: '%app.photo_variation_cache_path%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Actions\:
        resource: '../src/Actions/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Infrastructure\Migration\RootMigrationsFilesystem:
        arguments:
            $versionDirectoryParameter: 'ez_migration_bundle.version_directory'
    ez_migration_bundle.loader:
        alias: App\Infrastructure\Migration\RootMigrationsFilesystem

    App\Infrastructure\FieldTypes\Photo\Type:
        tags:
            - { name: ibexa.field_type, alias: mlphoto }
    App\Infrastructure\FieldTypes\Photo\PhotoConverter:
        tags:
            - { name: ibexa.field_type.storage.legacy.converter, alias: mlphoto }