name: Building the project and running the test suite
on: [push, pull_request]
jobs:
    project:
        name: Slide Show project
        runs-on: ubuntu-latest
        container: ezsystems/php:8.1-node16

        # Docs: https://docs.github.com/en/actions/using-containerized-services
        services:
            mysql:
                image: mariadb:10.9.4
                env:
                    MYSQL_ROOT_PASSWORD: root
        env:
            APP_ENV: test
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                path: vendor
                key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                  ${{ runner.os }}-php-

            - name: Install Composer dependencies and boot php generated encore dependencies
              run: |
                  composer install --no-progress --prefer-dist --optimize-autoloader --no-scripts
                  composer run auto-scripts -n

            - name: Create database
              run: |
                  php bin/console ibexa:install ibexa-oss || echo "Failed to create base CMS database"

            - name: Cache Yarn packages
              id: yarn-cache
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-php-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install Yarn dependencies and build front assets
              run: |
                  yarn install --frozen-lockfile
                  yarn run build
            - name: Migrate DB
              run: composer run migrate_db -n
            - name: Migrate the DB and run tests
              run: composer run test